### PR TITLE
Threaded support

### PR DESCRIPTION
**Pull request by johnf**
This pull request has 2 changes

The first fixes up the gemspec with README.rdoc -> README.md

The second add some extra methods like put_tube. Same as put with a tube argument. It then wraps the use and put in a lock so you don't put things on the wrong tube in threaded environments

### CODE REVIEW

**Comment by kr** [comment]
This isn't sufficient to make a Beanstalk::Connection safe to use
from multiple threads at the same time. Individual requests
would still be interleaved.

**Comment by johnf** [comment]
@kr Why not? Individual requests would be interleaved, but they are always going to be. I don't see that as being a problem. i.e. You have the same problem with different processes or servers.

The problem this tries to solve is the classic

Thread A: use tubeA
Thread B: use tubeB
Thread A: put
Thread B: put

Now Thread A put its job on TubeB instead of TubeA

**Comment by kr** [comment]
Interleaving individual requests on a single connection produces garbage.
Say threads A and B each want to send "stats\r\n":

```
statsts\rats\r\n\n
```

kr

**Comment by johnf** [comment]
I think that is already covered. There is already a mutex around the socket.write. I think I worked out a better way of doing this which makes the API a bit cleaner. Going to give it a whirl and then update the pull request

**Comment by johnf** [comment]
OK this works a bit differently now. Instead of all the added calls to the API. We just add one new call that takes a block.
e.g.

```
Rather than have new API calls to specify the tube you want to be
threadsafe. Instead we wrap a block. e.g.

    beanstalk.on_tube('foo') do |connection|
      connection.put 'bar'
    end
```

Might be a better method name than on_tube but I don't think it's too bad

**Comment by kr** [comment]
I picked a simple example, but there are other ways requests
can be interleaved. If threads A and B send stats and put
requests, respectively, they can read the responses in the
wrong order. For example,

A sends stats
B sends put
B reads stats response intended for A
A reads put response intended for B

**Comment by johnf** [comment]
That's not possible from my reading of the code. All the calls use interact, look at the code below linked below

https://github.com/kr/beanstalk-client-ruby/blob/master/lib/beanstalk-client/connection.rb#L180

The request/response for each call is wrapped in a mutex. So in your example above B couldn't write to the socket until A has read back form it. i.e. B would block

**Comment by kr** [comment]
Wow, I honestly forgot that was there.

Can you rebase this as a single commit? I'll merge it in.
(Leave out the README.rdoc rename; that's a separate issue.)

kr

**Comment by johnf** [comment]
OK now rebased also updated readme to remove the note about threaded envrionments

**Pull request merged**
