### PR TITLE
First stab at a better readme

### PR DESCRIPTION
**Pull request by nesquena**
Hey Keith, I added a more complete readme for the ruby beanstalk client, included in this pull request. This is the first part of an attempt me and @Nico-Taing are making to improve beanstalk documentation. 

Nico has also ported your protocol to an easily readable and well-formatted markdown file which will come in a separate pull request.

Let me know if there's anything else you'd like me to add / correct or if there's any reason not to include a clearer readme.

### CODE REVIEW

**Comment by nesquena** [comment]
Also would recommend generating a github automatic website for this gem based on the readme. Looks something like this: http://nesquena.github.com/beanstalk-client-ruby/

**Comment by kr** [comment]
This looks awesome. Thanks.

**Comment by kr** [comment]
I generated an automatic github page as you suggested.

I also added you both as collaborators. Feel free to make
any commits you see fit in the future.

**Comment by nesquena** [comment]
Thanks, will continue working to improve the client in any way that I can.

**Pull request merged**
